accelerate launch WAN_test.py \
  --dataset_base_path data/example_video_dataset \
  --dataset_metadata_path data/example_video_dataset/metadata.csv \
  --height 512 \
  --width 512 \
  --dataset_repeat 100 \
  --model_id_with_origin_paths "Wan-AI/Wan2.2-TI2V-5B:diffusion_pytorch_model*.safetensors,Wan-AI/Wan2.2-TI2V-5B:models_t5_umt5-xxl-enc-bf16.pth,Wan-AI/Wan2.2-TI2V-5B:Wan2.2_VAE.pth" \
  --learning_rate 1e-5 \
  --num_epochs 2 \
  --remove_prefix_in_ckpt "pipe.dit." \
  --trainable_models "dit" \
  --condition_list "image,position,normals,dist_to_sphere,dir_to_sphere" \
  --targets "sphere_0,sphere_1" \
  --save_steps 10000 \
  --num_steps 150000 \
  --validation_every_steps 100  \
  --dataset_num_workers 8 \
  --trained_weights_path "../checkpoints/Wan_19oct/step-250000.safetensors"  \
  --data_path "../datasets/classroom" \
  --out_path "../outputs/classroom_video" \
  --evs "0,-3,-6,-9,-12" \
  --num_frames 21